# Generated by Django 4.1.6 on 2023-02-10 22:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer_name', models.CharField(blank=True, max_length=128, null=True)),
                ('customer_id', models.CharField(max_length=50, unique=True)),
                ('customer_property', models.CharField(choices=[('Presales', 'Presales'), ('Existing', 'Existing'), ('Terminated', 'Terminated')], max_length=10, verbose_name='Task status')),
                ('am', models.CharField(blank=True, max_length=128, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
