# Generated by Django 4.1.6 on 2023-02-11 16:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0003_subscription'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subscription',
            name='customer_id',
            field=models.IntegerField(),
        ),
    ]
