# Generated by Django 4.1.6 on 2023-02-11 16:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0004_alter_subscription_customer_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='subscription',
            old_name='customer_property',
            new_name='product',
        ),
    ]
