# Generated by Django 4.1.6 on 2023-02-11 16:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0005_rename_customer_property_subscription_product'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subscription',
            name='service_id',
            field=models.CharField(blank=True, max_length=50, null=True, unique=True),
        ),
    ]
