# Generated by Django 4.1.6 on 2023-02-16 20:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0010_alter_subscription_product'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subscription',
            name='service_id',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
