# Generated by Django 4.1.6 on 2023-02-22 02:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0012_alter_subscription_service_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='BillingSummary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('billing_id', models.CharField(blank=True, max_length=255, null=True)),
                ('customer_id', models.CharField(blank=True, max_length=255, null=True)),
                ('service_id', models.CharField(blank=True, max_length=255, null=True, unique=True)),
                ('year', models.CharField(blank=True, max_length=255, null=True)),
                ('month', models.CharField(blank=True, max_length=255, null=True)),
                ('percentile_98_h', models.IntegerField(blank=True, null=True)),
                ('percentile_98_hm', models.IntegerField(blank=True, null=True)),
                ('percentile_98', models.IntegerField(blank=True, null=True)),
                ('percentile_98_m', models.IntegerField(blank=True, null=True)),
                ('history', models.TextField(blank=True, null=True)),
                ('prefixes', models.TextField()),
                ('cir', models.IntegerField(blank=True, null=True)),
                ('pir', models.IntegerField(blank=True, null=True)),
                ('percentile_mbps_98', models.IntegerField(blank=True, null=True)),
                ('fqdn_subscribed', models.TextField(blank=True, null=True)),
                ('fqdn_additional', models.TextField(blank=True, null=True)),
                ('pricing', models.CharField(blank=True, max_length=255, null=True)),
                ('prefixes_done', models.IntegerField(blank=True, null=True)),
                ('monthly_report_done', models.IntegerField(blank=True, default=0, null=True)),
                ('order', models.CharField(blank=True, max_length=255, null=True)),
                ('sales_tag', models.CharField(blank=True, max_length=255, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
            ],
        ),
    ]
