# Generated by Django 4.1.6 on 2023-02-22 03:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0015_alter_billingsummary_prefixes_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='billingsummary',
            name='service_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
