# Generated by Django 4.1.6 on 2023-02-22 03:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0016_alter_billingsummary_service_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='billingsummary',
            name='prefixes',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
