# Generated by Django 4.1.6 on 2023-02-22 07:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0017_alter_billingsummary_prefixes'),
    ]

    operations = [
        migrations.CreateModel(
            name='BillingSummaryAggregates',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('group_name', models.CharField(max_length=255, null=True)),
                ('year', models.CharField(blank=True, max_length=255, null=True)),
                ('month', models.CharField(blank=True, max_length=255, null=True)),
                ('billing_list', models.JSONField(blank=True, null=True)),
                ('percentile_98_h', models.IntegerField(blank=True, null=True)),
                ('percentile_98_hm', models.IntegerField(blank=True, null=True)),
                ('percentile_98', models.IntegerField(blank=True, null=True)),
                ('percentile_98_m', models.IntegerField(blank=True, null=True)),
                ('percentile_mbps_98', models.IntegerField(blank=True, null=True)),
                ('data_progress', models.CharField(blank=True, max_length=255, null=True)),
                ('monthly_report_done', models.IntegerField(blank=True, default=0, null=True)),
                ('sequence', models.IntegerField(blank=True, default=1, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
            ],
        ),
    ]
