# Generated by Django 4.1.6 on 2023-02-27 05:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0018_billingsummaryaggregates'),
    ]

    operations = [
        migrations.CreateModel(
            name='BillingSetting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer_id', models.IntegerField()),
                ('service_id', models.IntegerField()),
                ('billing_id', models.CharField(max_length=255)),
                ('cir', models.IntegerField(blank=True, null=True)),
                ('pir', models.IntegerField(blank=True, null=True)),
                ('provisioned_at', models.CharField(blank=True, max_length=255, null=True)),
                ('terminated_at', models.CharField(blank=True, max_length=255, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
            ],
        ),
    ]
