# Generated by Django 4.1.6 on 2023-02-27 07:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0020_sensor_sensorbillingsettingmapping'),
    ]

    operations = [
        migrations.AddField(
            model_name='sensor',
            name='billing_setting',
            field=models.ManyToManyField(related_name='billing_related', to='billing.billingsetting'),
        ),
        migrations.DeleteModel(
            name='SensorBillingSettingMapping',
        ),
    ]
