# Generated by Django 4.1.6 on 2023-02-27 07:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0021_sensor_billing_setting_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sensor',
            name='billing_setting',
        ),
        migrations.AddField(
            model_name='sensor',
            name='billing_settings',
            field=models.ManyToManyField(related_name='billing_setting_related', to='billing.billingsetting'),
        ),
    ]
