# Generated by Django 4.1.6 on 2023-02-27 07:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0022_remove_sensor_billing_setting_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sensor',
            name='billing_settings',
        ),
        migrations.AddField(
            model_name='sensor',
            name='billing_settings',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='billing.billingsetting'),
        ),
    ]
