# Generated by Django 4.1.6 on 2023-02-27 08:08

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0023_remove_sensor_billing_settings_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sensor',
            name='billing_settings',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='sensors', to='billing.billingsetting'),
            preserve_default=False,
        ),
    ]
