# Generated by Django 4.1.6 on 2023-02-28 04:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0024_alter_sensor_billing_settings'),
    ]

    operations = [
        migrations.CreateModel(
            name='BillingSettingAggregates',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('group_name', models.CharField(max_length=255, null=True)),
                ('billing_list', models.JSONField(blank=True, null=True)),
                ('cir', models.IntegerField(blank=True, null=True)),
                ('pir', models.IntegerField(blank=True, null=True)),
                ('permanent', models.CharField(blank=True, max_length=255, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
            ],
        ),
    ]
