# Generated by Django 4.1.6 on 2023-03-02 03:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0025_billingsettingaggregates'),
    ]

    operations = [
        migrations.RenameField(
            model_name='sensor',
            old_name='sensor',
            new_name='sensor_id',
        ),
    ]
