# Generated by Django 4.1.6 on 2023-03-05 07:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0027_sensor_channel_list'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sensor',
            name='billing_settings',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sensors', to='billing.billingsetting'),
        ),
    ]
