version: '3.5'
services:

    web:
      build: ./billing-backend
      container_name: billing-api
      entrypoint: /docker_api/docker-entrypoint.sh
      command: python manage.py runserver 0.0.0.0:8000
      restart: always

      # ref.
      # https://docs.djangoproject.com/en/3.0/ref/django-admin/#django-admin-createsuperuser
      environment:
        - DJANGO_SUPERUSER_USERNAME=rdadmin
        - DJANGO_SUPERUSER_PASSWORD=1qaz@WSX
        - DJANGO_SUPERUSER_EMAIL=allen.chen@greatforti.com

      volumes:
        - api_data:/billing-backend
        # (HOST:CONTAINER)
      ports:
        - "8000:8000"
        # (HOST:CONTAINER)
      networks:
        - proxy
      logging:
        driver: "json-file"
        options:
          max-file: "1"    # default 是 1
          max-size: "200m" # default 是 -1, 也就是沒有限制

volumes:
    api_data:

networks:
    proxy:
      # external:
        name: my_network